alias fiji='~/fiji/Fiji.app/ImageJ-linux64'
alias sau='sudo apt update'
alias fx='cd /media/john/sys2/web18/java/fracgen'
alias rfx='java -cp /media/john/sys2/imageJ/jars/ImageJ/ij.jar:. -Xmx8g FracGenWX -c8m -RR -! -H -C'
alias m='mkdir'
alias ffx='java -cp /media/john/sys2/imageJ/jars/ImageJ/ij.jar:. -Xmx8g FracGenWX -c6m -! -H -C'
alias tsdemo='ffx -f277 -g80'
alias cfx='javac -cp /media/john/sys2/imageJ/jars/ImageJ/ij.jar:. FracGenWX.java'
alias panel='xfce4-panel -p'
alias pg='cd /media/john/sys2/web18/playground'
alias disp=xfce4-display-settings
alias b=". ~/.bash_aliases"
alias ..="cd .."
alias ...="cd ../.."
alias p="ping -c 6 8.8.8.8"
alias sau='sudo apt update'
alias x='xdg-open'
alias gl='git log --oneline'
alias g=glslViewer
alias gf="wmctrl -r glslViewer -b add,fullscreen"
alias sib=".. && cd"
alias upg='sudo apt upgrade'
alias fupg='sudo apt full-upgrade'
alias sai='sudo apt install'
alias xr='xfce4-panel -r && xfwm4 --replace'
alias p5='cd /mnt/zeta/web19/code-institute/milestone-projects/project-5/'
alias py='python3'
alias sq='sqlite3'
alias gs='git status'
alias gp='git push '
alias gc='git commit -m'
alias s='cd ~/scratch'
alias rd=rmdir
alias t='. take.sh'
alias gpu='git push -u origin master'
alias t2='tree -L 2'
alias .m='cd -'
alias cs='mv /mnt/zeta/web19/code-institute/milestone-projects/project-5/fractrig/ft/lib/python3.7/site-packages/django/contrib/admin/static /mnt/zeta/web19/code-institute/milestone-projects/project-5/fractrig/ft/lib/python3.7/site-packages/django/contrib/admin/static_temp && python3 manage.py collectstatic && mv /mnt/zeta/web19/code-institute/milestone-projects/project-5/fractrig/ft/lib/python3.7/site-packages/django/contrib/admin/static_temp /mnt/zeta/web19/code-institute/milestone-projects/project-5/fractrig/ft/lib/python3.7/site-packages/django/contrib/admin/static'
alias gcom='echo $(git rev-list HEAD --count) commits\!'
alias k='pkill -f'
alias mem='sudo dmidecode --type 17'
alias alarm='chromium-browser file:///media/john/sys2/web18/playground/javascript/javascript-30/02-clock/index.html'
alias tinto='cd /media/john/sys2/web18/playground/COLOURS'
alias bs='browser-sync --server --watch'
alias h='history | grep'
alias u='unclutter -idle .000001 -jitter 2000 &'
alias vis='cd /media/john/sys2/web18/playground/visuals'
alias zzz='. sustil.sh'
alias repos='py /media/john/sys2/web18/playground/python/github_api/list_repos.py'
alias cn='cat --number'
alias r='. rep.sh'
alias lll='du -h * -d0*'
alias ddlog="sudo kill -USR1 $(pgrep -l '^dd$' | sed 's/.\{2\}$//')"

alias n='uname -n'
alias cv='cd /mnt/zeta/web19/code-institute/milestone-projects/project-1/site/media/old-cvs'
alias t1='tree -L 1'
alias mr='python3 /media/john/sys2/web18/playground/python/sockets/molerat.py'
alias www='. www.sh'
